import { ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { createTransfer } from "@/features/transactions/transfer-actions";
import { requireUser } from "@/lib/supabase/server";

export const metadata={title:"โอนเงิน"};
export default async function TransferPage({searchParams}:{searchParams:Promise<{error?:string}>}){const params=await searchParams;const{supabase,userId}=await requireUser();const{data,error}=await supabase.from("accounts").select("id,name").eq("owner_id",userId).eq("is_active",true).order("name");if(error)throw error;const current=new Date();const now=new Date(current.getTime()-current.getTimezoneOffset()*60000).toISOString().slice(0,16);return <div className="mx-auto max-w-2xl"><div className="mb-5"><p className="text-sm text-muted-foreground">ลดต้นทางและเพิ่มปลายทางแบบ atomic</p><h1 className="mt-1 text-2xl font-bold">โอนเงินระหว่างบัญชี</h1></div><Card><CardHeader><CardTitle>รายละเอียดการโอน</CardTitle><CardDescription>การโอนไม่เป็นรายรับหรือรายจ่ายรวม ค่าธรรมเนียมจะเป็นรายจ่ายแยก</CardDescription></CardHeader><CardContent>{params.error&&<p role="alert" className="mb-4 rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{params.error}</p>}{(data?.length??0)<2?<p className="text-sm text-muted-foreground">ต้องมีบัญชีที่ใช้งานอย่างน้อย 2 บัญชี</p>:<form action={createTransfer} className="space-y-4"><div className="grid items-end gap-3 sm:grid-cols-[1fr_auto_1fr]"><label><Label>จากบัญชี</Label><select name="sourceAccountId" className="mt-1.5 min-h-11 w-full rounded-xl border bg-background px-3">{data?.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><ArrowRight className="mb-3 hidden size-5 text-muted-foreground sm:block"/><label><Label>ไปบัญชี</Label><select name="destinationAccountId" className="mt-1.5 min-h-11 w-full rounded-xl border bg-background px-3">{data?.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div><div className="grid grid-cols-2 gap-3"><label><Label>ยอดโอน (บาท)</Label><Input name="amount" inputMode="decimal" required /></label><label><Label>ค่าธรรมเนียม (บาท)</Label><Input name="fee" inputMode="decimal" defaultValue="0.00" required /></label></div><label><Label>วันที่และเวลา</Label><Input name="occurredAt" type="datetime-local" defaultValue={now} required /></label><label><Label>รายละเอียด</Label><Input name="description" defaultValue="โอนระหว่างบัญชี" required /></label><div className="rounded-xl border bg-secondary/40 p-4 text-sm">เมื่อยืนยัน ระบบจะล็อกทั้งสองบัญชีและบันทึก ledger ทั้งสองฝั่งใน database transaction เดียว</div><Button className="w-full" type="submit">ตรวจแล้ว ยืนยันการโอน</Button></form>}</CardContent></Card></div>}
